root_dir: ${env:ROOT}
seed: 12345
seq: 'MSTKKKPLTQEQLEDARRLKAIYEKKKNELGLSQESVADKMGMGQSGVGALFNGINALNAYNAALLTKILKVSVEEFSPSIAREIYEMYEAVSMQPSLRSEYEYPVFSHVQAGMFSPELRTFTKGDAERWVSTTKKASDSAFWLEVEGNSMTAPTGSKPSFPDGMLILVDPEQAVEPGDFCIARLGGDEFTFKKLIRDSGQVFLQPLNPQYPMIPCNESCSVVGKVIASQWPEETFG'

train:
  epochs: 20

model:
  num_steps: 20
  embedding_dim: 64
  num_layers: 3
  hidden_size: 64
  lr: 1e-4
  weight_decay: 1e-3
  device: 'cuda'

data:
  generate: True
  max_num: 10000
  max_mut: 20
  batch_size: 256
